name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 触发于标签如 v1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.24'  # 使用您的Go版本
    - name: Build Windows amd64
      run: GOOS=windows GOARCH=amd64 go build -o yaml-editor-windows-amd64.exe
    - name: Build macOS amd64
      run: GOOS=darwin GOARCH=amd64 go build -o yaml-editor-darwin-amd64
    - name: Build macOS arm64
      run: GOOS=darwin GOARCH=arm64 go build -o yaml-editor-darwin-arm64
    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -o yaml-editor-linux-amd64
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated build for ${{ github.ref }}.
          Run the executable and access http://localhost:8080 for WebUI.
        draft: false
        prerelease: false
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: yaml-editor-windows-amd64.exe
        asset_name: yaml-editor-windows-amd64.exe
        asset_content_type: application/octet-stream
    - name: Upload macOS amd64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: yaml-editor-darwin-amd64
        asset_name: yaml-editor-darwin-amd64
        asset_content_type: application/octet-stream
    - name: Upload macOS arm64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: yaml-editor-darwin-arm64
        asset_name: yaml-editor-darwin-arm64
        asset_content_type: application/octet-stream
    - name: Upload Linux amd64 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: yaml-editor-linux-amd64
        asset_name: yaml-editor-linux-amd64
        asset_content_type: application/octet-stream