name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 触发于标签如 v1.0

permissions:
  contents: write  # 显式授予写权限，用于创建Release和上传资产

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # 更新到v4
    - uses: actions/setup-go@v5  # 更新到v5
      with:
        go-version: '1.21'  # 您的Go版本
    - name: Build Windows amd64
      run: GOOS=windows GOARCH=amd64 go build -o yaml-editor-windows-amd64.exe
    - name: Build macOS amd64
      run: GOOS=darwin GOARCH=amd64 go build -o yaml-editor-darwin-amd64
    - name: Build macOS arm64
      run: GOOS=darwin GOARCH=arm64 go build -o yaml-editor-darwin-arm64
    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -o yaml-editor-linux-amd64
    - name: Release
      uses: softprops/action-gh-release@v2  # 使用现代action，简化Release和上传
      with:
        body: |
          Automated build for ${{ github.ref }}.
          Run the executable and access http://localhost:8080 for WebUI.
        files: |
          yaml-editor-windows-amd64.exe
          yaml-editor-darwin-amd64
          yaml-editor-darwin-arm64
          yaml-editor-linux-amd64